$ANSIBLE_VAULT;1.1;AES256
30613239336565333330303939396631316562353733663564386439633731363937616331326436
6166663162386461633536333434363765353436663038360a396230343566643262396262616134
32626531376437356530646334636639643832373437393730373133636331323864363133303533
3264653238363336300a626561383137663538313166613034646264616363306561623864333264
34623961316462323836613732623264633965633766633931623362656261653936363737383138
65313736626564306332653238623034383966616237643537633464383161376537396635393731
38636162343365656135393430323866316235303066666435323838613131383132383535363733
30643762616435666335323964613732623765663234306231313462623736663838346231636235
33653962316231643266613761656561386434313532653931343232326664396333323164653937
33623533316362323363366330613930663636306232313866313565353338363462336337303631
61666538656438333338306332313966613238623033323031646133313664303563666330663234
64623839336430656530373730636534313635326630333664336264333931356533306437633239
63626130633038396132626634303932386130303438303136303330653534356162613538626364
64633832373433313036653232646539653565343630383638623535346262633064303365326362
32396636313633373632393631386161346430363964656534346332656637336664336563663561
62333337616239396338
